server:
   port: 5000

spring:
   datasource:
      url: jdbc:h2:mem:bancotest
      username: admin
      password: admin
      driverClassName: org.h2.Driver
   h2: 
      console:
        path: /h2-console
        enabled: true
        settings.web-allow-others: true
   jpa:
      hibernate.ddl-auto: validate    
# Flyway Config
flyway:
   url: jdbc:h2:mem:bancotest
   baseline-on-migrate: true
   enabled: true
   validate-on-migrate: true
      