server:
   port: 5000
   app:
      client:
          id:     "exemploaplicativocliente"
          secret: "9834ba657bb2c60b5bb53de6f4201905"
sonar:
   host:
      url: 172.20.0.7

spring:
   datasource:
      url: jdbc:h2:mem:bancotest;MODE=MYSQL
      username: admin
      password: admin
      driverClassName: org.h2.Driver
   h2: 
      console:
        path: /h2-console
        enabled: true
        settings.web-allow-others: true
   jpa:
      hibernate.ddl-auto: none   
# Flyway Config
flyway:
   url: jdbc:h2:mem:bancotest
   baseline-on-migrate: true
   enabled: true
   validate-on-migrate: true


# Log4j - Log
logging:
    file: app.log  
      