CREATE TABLE FIXED_EXPENSE(
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    usuario_id VARCHAR(36) NOT NULL,
    TYPE_FIXED_EXPENSE_ID VARCHAR(36) NOT NULL,
    value_spent NUMERIC(10,2) DEFAULT 0,
    due_date DATE DEFAULT NULL,
    has_historic BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_usu_desp_fix_id FOREIGN KEY(usuario_id) REFERENCES usuario(id),
    CONSTRAINT fk_TYPE_FIXED_EXPENSE_id FOREIGN KEY(TYPE_FIXED_EXPENSE_ID) REFERENCES TYPE_FIXED_EXPENSE(id)
);
