
jwt.secret: "teste123"
url.retrieve.stocks.data: https://query1.finance.yahoo.com/v7/finance/download/
# 24h in millisecond
security:
       jwt:
          expiration-time: 86400000
          secretKey: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"
server:
    port: 5000

#Banco de Dados Local
spring:
    jackson: 
      time-zone: America/Sao_Paulo
    datasource:
      url: jdbc:h2:mem:bancotest;MODE=MYSQL
      username: admin
      password: admin
      driverClassName: org.h2.Driver
    h2: 
      console:
           path: /h2-console
           enabled: true
           settings.web-allow-others: true
    jpa: 
       hibernate.ddl-auto: update     
    profiles:
       active: test
flyway:
   url: jdbc:h2:mem:bancotest
   baseline-on-migrate: true
   enabled: true
   validate-on-migrate: true

 # Logging do Servidor  